version: '3.8'
services:
  pg-dev:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ecommerce
    volumes:
     - pgdata:/data/postgres
  app:
      build: .
      container_name: api-e-commerce
      restart: always
      ports:
        - 4000:4000
      volumes:
        - .:/usr/app
      links:
        - pg-dev
      depends_on:
        - pg-dev
volumes:
  pgdata:
    driver: local